Repository DTStack/dt-utils, pull requests merged in 2021-09, with the labels that each got.

#18 Feat dt common
  docs/_sidebar.md
  docs/dateTime.md
  package.json
  src/cookie.ts
  src/dateTime.ts
  src/index.ts
  src/localDB.ts
  src/utils.ts
  test/dateTime.test.ts
  test/localDB.test.ts
  yarn.lock
Labels: feature

#24 Feat migrate is obj
  docs/utils.md
  src/utils.ts
  test/utils.test.ts
Labels: feature

#22 Feat migrate is empty
  docs/utils.md
  src/utils.ts
  test/utils.test.ts
Labels: feature

#23 Feat migrate transform array
  docs/utils.md
  src/utils.ts
  test/utils.test.ts
Labels: feature

#33 feat: add mergeObj fn
  .editorconfig
  .gitignore
  docs/utils.md
  package.json
  src/utils.ts
  test/utils.test.ts
  yarn.lock
Labels: documentation, enhancement, new-util

#40 refactor: remove appinfo
  docs/utils.md
  src/utils.ts
Labels: enhancement
